export const actionType = {
  SET_USER: "SET_USER",
  SET_TOKEN: "SET_TOKEN",
  SET_POSTS: "SET_POSTS",
  SET_POST: "SET_POST",
  SET_SINGLE_POST: "SET_SINGLE_POST",
  SET_COMMENT: "SET_COMMENT",
  SET_ERROR: "SET_ERROR",
  DELETE_POST: "DELETE_POST",
  DELETE_COMMENT: "DELETE_COMMENT",
  SET_MSG: "SET_MSG",
  LOGOUT: "LOGOUT",
}
